export const getMockCourses = () => [
  {
    id: 1,
    codigo: "SIS-101",
    nombre: "Sistemas de Informacion",
    seccion: "A",
    docente: "Otto Ortiz",
    horario: "07:00 - 08:30",
    aula: "Laboratorio 1",
    estado: true,
  },
  {
    id: 2,
    codigo: "BD2-202",
    nombre: "Bases de Datos II",
    seccion: "B",
    docente: "Carlos Mendez",
    horario: "08:40 - 10:10",
    aula: "Salon 4",
    estado: true,
  },
  {
    id: 3,
    codigo: "PRO-303",
    nombre: "Programacion III",
    seccion: "A",
    docente: "Maria Lopez",
    horario: "10:20 - 11:50",
    aula: "Laboratorio 2",
    estado: false,
  },
  {
    id: 4,
    codigo: "RED-210",
    nombre: "Redes de Computadoras",
    seccion: "C",
    docente: "Juan Perez",
    horario: "13:00 - 14:30",
    aula: "Salon 7",
    estado: true,
  },
  {
    id: 5,
    codigo: "ING-110",
    nombre: "Ingenieria de Software",
    seccion: "A",
    docente: "Ana Garcia",
    horario: "14:40 - 16:10",
    aula: "Salon 3",
    estado: true,
  },
  {
    id: 6,
    codigo: "MAT-120",
    nombre: "Matematica Aplicada",
    seccion: "B",
    docente: "Luis Ramirez",
    horario: "16:20 - 17:50",
    aula: "Salon 5",
    estado: true,
  },
];
